# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
vagrant_box_name = ENV['VAGRANT_BOXNAME'] || "kali-pwnbox"
vbox_vm_name = ENV['VBOX_BOXNAME'] || "kali-vagrant"
cpus = ENV['VAGRANT_CPU'] || 4
ram = ENV['VAGRANT_RAM'] || 16384
hostname = ENV['VAGRANT_HOSTNAME'] || "kali"
gui = ENV['GUI'] || "false"


Vagrant.require_version ">= 1.8.0"
Vagrant.configure("2") do |config|
  config.vm.define "custom-kali" do |vm|
    config.vm.box = vagrant_box_name.to_s
    
    # Can be changed, but username of base box needs to be changed in preseed.cfg
    config.ssh.username = "somepwnpun"

    # Securely changed at the end of provisioning
    config.ssh.sudo_command = "echo 'kali' | sudo -S %c"

    config.vm.provider "virtualbox" do |v|
      v.name = vbox_vm_name
      v.check_guest_additions = true
      v.gui = gui
      v.memory = ram.to_s
      v.cpus = cpus.to_i
      #v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      #v.customize ["storageattach", :id, "--storagectl", "IDE Controller", "--port", "0", "--device", "1", "--type", "dvddrive", "--medium", "emptydrive"]
    end
    config.vm.synced_folder "/home/seili/Workspace/CTF/VPNs", "/home/somepwnpun/CTF/VPNs"
    config.vm.synced_folder "/home/seili/Workspace/CTF/Dots", "/home/somepwnpun/CTF/Dots"
    config.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "build/build.yml"
      ansible.extra_vars = {
        # Securely changed at the end of provisioning
        ansible_become_pass: "kali"
      }
      ansible.compatibility_mode = "2.0"
      ansible.skip_tags = "cloud", "binex"
      ansible.vault_password_file = "vaultpass.txt"
    end
  end
end
