---
# TODO: Opportunity for futher customization
# - name: Add pywal
#   community.general.pipx:
#     name: pywal
#     state: present
#   become: true
#   become_user: "{{ username | default('vagrant')}}"
#   tags: rice 

# - name: pipx ensurepath
#   shell: pipx ensurepath
#   become: true
#   become_user: "{{ username | default('vagrant')}}"

# - name: Add imagemagic dependency
#   apt: 
#     pkg: imagemagick
#     state: present

# - name: Run pywal
#   shell:
#     cmd: wal -i /usr/share/backgrounds/xfce/xfce-leaves.svg && wal -R
#   become: true
#   tags: rice

# - name: Add pywal to .zshrc
#   lineinfile:
#     path: "/home/{{ username | default('vagrant')}}/.zshrc"
#     line: "wal -R"
#     insertafter: EOF
#     state: present
#   become: true
#   become_user: "{{ username | default('vagrant')}}"
#   tags: rice
# - name: Add Papirus Repo
#   shell: sudo add-apt-repository ppa:papirus/papirus
#   tags: rice
  
# - name: Install Papirus Icons
#   apt:
#     update_cache: true
#     name: papirus-icon-theme
#     state: present
#   become: true
#   tags: rice

- name: Install Powerline10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    depth: 1
    dest: ~/powerlevel10k
  tags: rice

- name: Create zshrc
  shell: echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc
  tags: rice

# for genmon: sh -c "ifconfig eth0 | grep -w inet | awk '{ print $2}'"
