---
# - name: Set Workspace Names
#   xfconf:
#     channel: xfwm4
#     property: /general/workspace_names
#     value_type: string
#     value: ['Term', 'Burp', 'Web', 'Tmp']
#   become_user: "{{ username }}"
#   environment:
#     DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
#   tags: rice

- name: Open Terminal with Super + Return
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: /commands/custom/<Super>Return
    value_type: string
    value: exo-open --launch alacritty
    state: present
  become_user: "{{ username }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  tags: rice

- name: Open Thunar with Super + E
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: /commands/custom/<Super>e
    value_type: string
    value: thunar
    state: present
  become_user: "{{ username }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  tags: rice

- name: App Finder Super + D
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: /commands/custom/<Super>d
    value_type: string
    value: xfce4-appfinder
    state: present
  become_user: "{{ username }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  tags: rice

- name: Quit Window Super + Q
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: /xfwm4/custom/<Super>q
    value_type: string
    value: close_window_key
    state: present
  become_user: "{{ username }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  tags: rice

- name: Remove Workspace 1
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: /xfwm4/custom/<Primary><Alt>1
    value_type: string
    value: Empty
    state: present
  become_user: "{{ username }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  tags: rice

- name: Remove Workspace 2
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: /xfwm4/custom/<Primary><Alt>2
    value_type: string
    value: Empty
    state: present
  become_user: "{{ username }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  tags: rice

- name: Remove Workspace 3
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: /xfwm4/custom/<Primary><Alt>3
    value_type: string
    value: Empty
    state: present
  become_user: "{{ username }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  tags: rice

- name: Remove Workspace 4
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: /xfwm4/custom/<Primary><Alt>4
    value_type: string
    value: Empty
    state: present
  become_user: "{{ username }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  tags: rice

- name: Workspace 1
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: /xfwm4/custom/<Super>1
    value_type: string
    value: workspace_1_key
    state: present
  become_user: "{{ username }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  tags: rice

- name: Workspace 2
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: /xfwm4/custom/<Super>2
    value_type: string
    value: workspace_2_key
    state: present
  become_user: "{{ username }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  tags: rice

- name: Workspace 3
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: /xfwm4/custom/<Super>3
    value_type: string
    value: workspace_3_key
    state: present
  become_user: "{{ username }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  tags: rice

- name: Workspace 4
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: /xfwm4/custom/<Super>4
    value_type: string
    value: workspace_4_key
    state: present
  become_user: "{{ username }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  tags: rice

- name: Move to Workspace 1
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: /xfwm4/custom/<Alt>1
    value_type: string
    value: move_window_workspace_1_key
    state: present
  become_user: "{{ username }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  tags: rice

- name: Move to Workspace 2
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: /xfwm4/custom/<Alt>2
    value_type: string
    value: move_window_workspace_2_key
    state: present
  become_user: "{{ username }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  tags: rice

- name: Move to Workspace 3
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: /xfwm4/custom/<Alt>3
    value_type: string
    value: move_window_workspace_3_key
    state: present
  become_user: "{{ username }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  tags: rice

- name: Move to Workspace 4
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: /xfwm4/custom/<Alt>4
    value_type: string
    value: move_window_workspace_4_key
    state: present
  become_user: "{{ username }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  tags: rice

- name: Clone XFCE rice repository
  git:
    repo: 'https://github.com/somepwnpun/kali-rice.git'
    dest: ~/kali-rice
    version: main
  tags: rice

- name: Copy XFCE configuration files
  copy:
    src: ~/kali-rice/.config/xfce4/
    dest: ~/.config/xfce4/
    owner: "{{ username }}"
    mode: 0755
    remote_src: yes
  tags: rice

- name: Copy themes
  copy:
    src: ~/kali-rice/.themes/
    dest: ~/.themes/
    owner: "{{ username }}"
    mode: 0755
    remote_src: yes
  tags: rice

- name: Copy fonts
  copy:
    src: ~/kali-rice/.fonts/
    dest: ~/.fonts/
    owner: "{{ username }}"
    mode: 0755
    remote_src: yes
  tags: rice

- name: Copy icons
  copy:
    src: ~/kali-rice/.icons/
    dest: ~/.icons/
    owner: "{{ username }}"
    mode: 0755
    remote_src: yes
  tags: rice

- name: Restart XFCE Panel
  shell: xfce4-panel -r
  tags: rice

