--- 
- name: Install prowler 
  community.general.pipx:
    name: prowler
    state: present
  become_user: "{{ username | default('vagrant')}}"
  tags: cloud

- name: Install scoutsuite
  community.general.pipx:
    name: scoutsuite
    state: present
  become_user: "{{ username | default('vagrant')}}"
  tags: cloud

#The below uses debian 12 bookworm as DIST_CODE as there is no kali release file
- name: Install Azure CLI
  shell: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo DIST_CODE=bookworm bash
  become: true 
  #become_user: "{{ username | default('vagrant')}}"
  tags: cloud

- name: Cloning Cloudsploit
  git: 
    repo: https://github.com/aquasecurity/cloudsploit.git
    dest: "{{ tools_destination_folder | default('$HOME/Tools') }}/cloudsploit"
  tags: cloud

- name: Building Cloudsploit Container 
  shell:
    chdir: "{{ tools_destination_folder | default('$HOME/Tools') }}/cloudsploit"
    cmd: docker build . -t cloudsploit:0.0.1
  become: true
  tags: cloud

- name: Install steampipe
  shell:
    chdir: "{{ tools_destination_folder | default('$HOME/Tools') }}"
    cmd: |
      mkdir steampipe
      cd steampipe
      sudo /bin/sh -c "$(curl -fsSL https://steampipe.io/install/steampipe.sh)"
  become: true
  #become_user: "{{ username | default('vagrant')}}"
  tags: cloud

- name: Install Powershell Azure CLI
  shell:
    cmd: pwsh -c ECHO A | pwsh -c Install-Module -Name Az
  become_user: "{{ username | default('vagrant')}}"
  tags: cloud

- name: Clone Powerzure
  git:
    repo: https://github.com/hausec/PowerZure.git
    dest: "{{ tools_destination_folder | default('$HOME/Tools') }}/PowerZure"
  tags: cloud

- name: Install Bloodhound
  apt:
    pkg: bloodhound
    state: latest
  become: true
  tags: cloud

# - name: Get latest AzureHound
#   community.general.github_release:
#     user: BloodHoundAD
#     repo: AzureHound
#     action: latest_release

#The below uses debian 12 bookworm as lsb_release -cs output as there is no kali release file
- name: Setup terraform apt cache 
  shell: 
    cmd: | 
      wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com bookworm main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
  become: true
  become_user: "{{ username | default('vagrant')}}"
  tags: cloud

- name: Install terraform 
  apt: 
    update_cache: yes 
    name: terraform
    state: latest
  become: true
  become_user: "{{ username | default('vagrant')}}"
  tags: cloud

- name: Installing kube-hunter Tool
  community.general.pipx:
    name: kube-hunter
  #become: true
  become_user: "{{ username | default('vagrant')}}"
  tags: cloud
